title: SdtElectronics
email: null@std.uestc.edu.cn
author: SdtElectronics

# Copyright setting
# You can use any html code, currently below placeholders are available:
# * current year: {currentYear}
# * author: {author} (Value is the same as site.author)
# * copyright: (c) - ©
# * copyleft: (cleft)
# * sound recording copyright: (p) - ℗ 
#
# For example:
#   "Copyright (c) 2017-{currentYear} <a href="https://example.com">{author}</a>"
#   "Copyright © 2017-2021 Foobar"
#
copyright: "Unpublished Work (cleft) 2017-{currentYear} {author}"

description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/jekyll-theme-antarctica" # the subpath of your site, e.g. /blog
url: "https://sdtelectronics.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
favicon: "" # the favicon for your site
#avatar: ""



template:
# date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
  date_format: "%b %d, %Y"
  widgets: colophon comment global_cmt post_meta share
  portfolios: projects gallery

# If you want to generate website sitemap, you can set true
# sitemap: false

# Valine Comments
valine:
  appId: "X0MYAuVgPxuPIwl5tDvbt1ab-MdYXbMMI"
  appKey: "2sNBzbQCo5BzNiBqMN2AioBd"

collections_dir: collections
collections:
  projects:
    output: true
  gallery:
    output: true
  
projects_categories: 
  - Hardware
  - Software
  - Documentation

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      avatar: "assets/img/a-default.png"

# Build settings
highlighter: rouge
markdown: kramdown
kmarkdown:
  input: GFM

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap